const { nameToId } = require('@frontiernav/graph')

const tileMappings = [
  { map_name: 'C.S.E.V. Maelstrom - Deck (Map)', game_id: 'ma03a_floor_03', name: 'C.S.E.V. Maelstrom - Deck (Tiles)' },
  { map_name: 'C.S.E.V. Maelstrom - Interior (Map)', game_id: 'ma03a_floor_01', name: 'C.S.E.V. Maelstrom - Interior (Tiles)' },
  { map_name: 'Ancient Ship - Deck', game_id: 'ma04a_f02', name: 'Ancient Ship - Deck (Tiles)' },
  { map_name: 'Ancient Ship - Mid-Deck', game_id: 'ma04a_f03', name: 'Ancient Ship - Mid-Deck (Tiles)' },
  { map_name: 'Ancient Ship - System Control Room', game_id: 'ma04a_f06', name: 'Ancient Ship - System - Control Room (Tiles)' },
  { map_name: 'Argentum - Bazaar', game_id: 'ma02a_f01', name: 'Argentum - Bazaar (Tiles)' },
  { map_name: 'Argentum - Lemour Inn', game_id: 'ma02a_f03', name: 'Argentum - Lemour Inn (Tiles)' },
  { map_name: 'Argentum - Flight Deck', game_id: 'ma02a_f05', name: 'Argentum - Flight Deck (Tiles)' },
  { map_name: 'Argentum - Wheelhouse', game_id: 'ma02a_f06', name: 'Argentum - Wheelhouse (Tiles)' },
  { map_name: "Argentum - Bana's Bedroom", game_id: 'ma02a_f07', name: "Argentum - Bana's Bedroom (Tiles)" },
  { map_name: 'Argentum - Noponya Shrine', game_id: 'ma02a_f08', name: 'Argentum - Noponya Shrine (Tiles)' },
  { map_name: 'Gormott - Lower Level', game_id: 'ma05a_f01', name: 'Gormott - Lower Level (Tiles)' },
  { map_name: 'Gormott - Upper Level - Right', game_id: 'ma05a_f02_shipoff', name: 'Gormott - Upper Level Right (No Ship) (Tiles)' },
  { map_name: 'Gormott - Upper Level - Right', game_id: 'ma05a_f02', name: 'Gormott - Upper Level Right (Ship) (Tiles)' },
  { map_name: 'Gormott - Torigoth Upper', game_id: 'ma05a_c_03_shipoff', name: 'Gormott - Torigoth Upper (No Ship) (Tiles)' },
  { map_name: 'Gormott - Torigoth Upper', game_id: 'ma05a_c_03', name: 'Gormott - Torigoth Upper (Ship) (Tiles)' },
  { map_name: 'Gormott - Torigoth Lower', game_id: 'ma05a_c_02', name: 'Gormott - Torigoth Lower (Tiles)' },
  { map_name: 'Gormott - Treepath', game_id: 'ma05a_c_01', name: 'Gormott - Treepath (Tiles)' },
  { map_name: 'Gormott - Ship Trashdump', game_id: 'ma05a_ship_f01', name: 'Gormott - Ship Trashdump (Tiles)' },
  { map_name: 'Gormott - Ship Cells', game_id: 'ma05a_ship_f02', name: 'Gormott - Ship Cells (Tiles)' },
  { map_name: 'Gormott - Ship Hangar', game_id: 'ma05a_ship_f03', name: 'Gormott - Ship Hangar (Tiles)' },
  { map_name: 'Gormott - Ship Wheelhouse', game_id: 'ma05a_ship_f04', name: 'Gormott - Ship Wheelhouse (Tiles)' },
  { map_name: 'Gormott - Upper Level - Left', game_id: 'ma05a_f05', name: 'Gormott - Upper Level Left (Tiles)' },
  { map_name: 'Uraya - Garfont', game_id: 'ma07a_a_floor_06', name: 'Uraya - Garfont (Tiles)' },
  { map_name: 'Uraya - Fonsa Myma', game_id: 'ma07a_c_floor_01', name: 'Uraya - Fonsa Myma (Tiles)' },
  { map_name: 'Uraya - Head', game_id: 'ma07a_a_floor_01', name: 'Uraya - Head (Tiles)' },
  { map_name: 'Uraya - Cataracts', game_id: 'ma07a_a_floor_05', name: 'Uraya - Cataracts (Tiles)' },
  { map_name: 'Uraya - Sternum Arch', game_id: 'ma07a_a_floor_03', name: 'Uraya - Sternum Arch (Tiles)' },
  { map_name: 'Uraya - Soulcrown Summit', game_id: 'ma07a_a_floor_04', name: 'Uraya - Soulcrown Summit (Tiles)' },
  { map_name: 'Uraya - Stomach', game_id: 'ma07a_b_floor_01', name: 'Uraya - Stomach (Tiles)' },
  { map_name: 'Uraya - Raqura Aquagardens', game_id: 'ma07a_b_floor_b01', name: 'Uraya - Raqura Aquagardens (Tiles)' },
  { map_name: 'Uraya - Olethro Ruins', game_id: 'ma07a_d_floor_01lodoff', name: 'Uraya - Olethro Ruins (Destroyed) (Tiles)' },
  { map_name: 'Uraya - Olethro Ruins', game_id: 'ma07a_d_floor_01', name: 'Uraya - Olethro Ruins (Intact) (Tiles)' },
  { map_name: 'Mor Ardain - Alba Cavanich', game_id: 'ma08a_city_f_3', name: 'Mor Ardain - Alba Cavanich (Tiles)' },
  { map_name: 'Mor Ardain - Palace Lower', game_id: 'ma08a_city_f_1', name: 'Mor Ardain - Palace Lower (Tiles)' },
  { map_name: 'Mor Ardain - Palace Upper', game_id: 'ma08a_city_f_4', name: 'Mor Ardain - Palace Upper (Tiles)' },
  { map_name: 'Mor Ardain - Lower Level', game_id: 'ma08a_rowf_1', name: 'Mor Ardain - Lower Level (Tiles)' },
  { map_name: 'Mor Ardain - Upper Level', game_id: 'ma08a_upf_1', name: 'Mor Ardain - Upper Level (Tiles)' },
  { map_name: 'Mor Ardain - Old Factory', game_id: 'ma08a_newplant_out', name: 'Mor Ardain - Old Factory (Tiles)' },
  { map_name: 'Temperantia - Peninsula', game_id: 'ma10a_f01', name: 'Temperantia - Peninsula (Tiles)' },
  { map_name: 'Temperantia - Central Plain', game_id: 'ma10a_f02', name: 'Temperantia - Central Plain (Tiles)' },
  { map_name: 'Temperantia - Judicium', game_id: 'ma10a_f03', name: 'Temperantia - Judicium (Tiles)' },
  { map_name: 'Indol - Goetius Port', game_id: 'ma11a_a_floor_01', name: 'Indol - Goetius Port (Tiles)' },
  { map_name: 'Indol - Sanctum', game_id: 'ma11a_a_floor_02', name: 'Indol - Sanctum (Tiles)' },
  { map_name: 'Indol - Ship', game_id: 'ma11a_b_floor_01', name: 'Indol - Ship (Tiles)' },
  { map_name: 'Tantal - Theosoir', game_id: 'ma13a_b_floor_01', name: 'Tantal - Theosoir (Tiles)' },
  { map_name: 'Tantal - Palace', game_id: 'ma13a_b_floor_05', name: 'Tantal - Palace (Tiles)' },
  { map_name: 'Tantal - Hall of Reception', game_id: 'ma13a_b_floor_02', name: 'Tantal - Hall of Reception (Tiles)' },
  { map_name: 'Tantal - Hall of Virtue', game_id: 'ma13a_b_floor_03', name: 'Tantal - Hall of Virtue (Tiles)' },
  { map_name: 'Tantal - Puresnow Passage', game_id: 'ma13a_b_floor_04', name: 'Tantal - Puresnow Passage (Tiles)' },
  { map_name: 'Tantal - Upper Level', game_id: 'ma13a_a_floor_01', name: 'Tantal - Upper Level (Tiles)' },
  { map_name: 'Tantal - Lower Level', game_id: 'ma13a_a_floor_06', name: 'Tantal - Lower Level (Tiles)' },
  { map_name: 'Tantal - Head', game_id: 'ma13a_a_floor_07', name: 'Tantal - Head (Tiles)' },
  { map_name: 'Leftheria - Fonsett', game_id: 'ma15a_f03', name: 'Leftheria - Fonsett (Tiles)' },
  { map_name: 'Leftheria - Rigitte Waters', game_id: 'ma15a_f01', name: 'Leftheria - Rigitte Waters (Tiles)' },
  { map_name: 'Leftheria - Cloudway', game_id: 'ma15a_f02', name: 'Leftheria - Cloudway (Tiles)' },
  { map_name: 'Leftheria - Fonsett Waters', game_id: 'ma15a_f04', name: 'Leftheria - Fonsett Waters (Tiles)' },
  { map_name: 'Spirit Crucible - Upper Level', game_id: 'ma16a_floor_01b', name: 'Spirit Crucible - Upper Level (Tiles)' },
  { map_name: 'Spirit Crucible - Bone Road', game_id: 'ma16a_floor_01', name: 'Spirit Crucible - Bone Road (Tiles)' },
  { map_name: 'Spirit Crucible - Mid Level', game_id: 'ma16a_floor_02', name: 'Spirit Crucible - Mid Level (Tiles)' },
  { map_name: 'Spirit Crucible - Cenotaph Bridge', game_id: 'ma16a_floor_08', name: 'Spirit Crucible - Cenotaph Bridge (Tiles)' },
  { map_name: 'Spirit Crucible - Lower Level', game_id: 'ma16a_floor_11', name: 'Spirit Crucible - Lower Level (Tiles)' },
  { map_name: 'Cliffs of Morytha - Upper Level (Map)', game_id: 'ma17a_f01', name: 'Cliffs of Morytha - Upper Level (Tiles)' },
  { map_name: 'Cliffs of Morytha - Lower Level (Map)', game_id: 'ma17a_f03_lodoff', name: 'Cliffs of Morytha - Lower Level (Destroyed) (Tiles)' },
  { map_name: 'Cliffs of Morytha - Lower Level (Map)', game_id: 'ma17a_f03', name: 'Cliffs of Morytha - Lower Level (Intact) (Tiles)' },
  { map_name: 'Cliffs of Morytha - Way of the Practitioner', game_id: 'ma17a_f03b', name: 'Cliffs of Morytha - Way of the Practitioner (Tiles)' },
  { map_name: 'Morytha - Streets', game_id: 'ma18a_f01', name: 'Morytha - Streets (Tiles)' },
  { map_name: 'Morytha - Decaying Titan', game_id: 'ma18a_f07', name: 'Morytha - Decaying Titan (Tiles)' },
  { map_name: 'Morytha - World Tree', game_id: 'ma18a_f11', name: 'Morytha - World Tree (Tiles)' },
  { map_name: 'World Tree - Lower Level (Map)', game_id: 'ma20a_f01', name: 'World Tree - Lower Level (Tiles)' },
  { map_name: 'World Tree - Lv. 2 Lower', game_id: 'ma20a_f02', name: 'World Tree - Lv. 2 Lower (Tiles)' },
  { map_name: 'World Tree - Lv. 2 Central', game_id: 'ma20a_f03', name: 'World Tree - Lv. 2 Central (Tiles)' },
  { map_name: 'World Tree - Sky Bridge', game_id: 'ma20a_f05', name: 'World Tree - Sky Bridge (Tiles)' },
  { map_name: 'World Tree - Mid Level (Map)', game_id: 'ma20a_f08_1', name: 'World Tree - Mid Level (Tiles)' },
  { map_name: 'World Tree - Lv. 3', game_id: 'ma20a_f09', name: 'World Tree - Lv. 3 (Tiles)' },
  { map_name: 'World Tree - Upper Level (Map)', game_id: 'ma20a_f10', name: 'World Tree - Upper Level (Tiles)' },
  { map_name: 'First Low Orbit Station - Upper Level (Map)', game_id: 'ma21a_a_floor_01', name: 'First Low Orbit Station - Upper Level (Tiles)' },
  { map_name: 'First Low Orbit Station - Elysium', game_id: 'ma21a_a_floor_02', name: 'First Low Orbit Station - Elysium (Tiles)' },
  { map_name: 'First Low Orbit Station - Lower Level (Map)', game_id: 'ma21a_b_floor_02', name: 'First Low Orbit Station - Lower Level (Tiles)' },
  { map_name: 'First Low Orbit Station - Hangar', game_id: 'ma21a_b_floor_03', name: 'First Low Orbit Station - Hangar (Tiles)' }
]
  .map(v => {
    v.id = nameToId(v.name)
    v.map_id = nameToId(v.map_name)
    return v
  })

const mapMappings = [
  { name: 'Argentum Trade Guild', game_id: 'ma02a' },
  { name: 'Gormott Province', game_id: 'ma05a' },
  { name: 'Kingdom of Uraya', game_id: 'ma07a' },
  { name: 'Empire of Mor Ardain', game_id: 'ma08a' },
  { name: 'Temperantia', game_id: 'ma10a' },
  { name: 'Indoline Praetorium', game_id: 'ma11a' },
  { name: 'Kingdom of Tantal', game_id: 'ma13a' },
  { name: 'Leftherian Archipelago', game_id: 'ma15a' },
  { name: 'Spirit Crucible Elpys', game_id: 'ma16a' },
  { name: 'Cliffs of Morytha', game_id: 'ma17a' },
  { name: 'Land of Morytha', game_id: 'ma18a' },
  { name: 'World Tree', game_id: 'ma20a' },
  { name: 'First Low Orbit Station', game_id: 'ma21a' },
  { name: 'C.S.E.V. Maelstrom', game_id: 'ma03a' },
  { name: 'Ancient Ship', game_id: 'ma04a' }
].map(v => {
  v.id = nameToId(v.name)
  return v
})

module.exports = {
  tileMappings,
  mapMappings
}
